# Generated by Django 5.2.2 on 2025-06-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='choice',
            new_name='type',
        ),
    ]
